### PR TITLE
OZ-196: Add parent POMs

### PR DESCRIPTION
**Pull request by ibacher**
@rbuisson So, part of our discussion was around having a parent POM for Ozone. This actually creates two, one specifically just to ensure plugin versions are the same across projects (so now `ozone` and `ozone-distro` inherit from this) and one that's the actual parent POM for "actual" distributions.

With this, the Kenya distribution POM can be reduced to:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.ozonehis</groupId>
    <artifactId>ozone-distro-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <groupId>org.kenyahmis</groupId>
  <artifactId>ozone-kenya</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <name>Ozone Kenya</name>

  <developers>
    <developer>
      <name>Palladium Developers</name>
    </developer>
  </developers>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <!-- TODO Add KenyaEMR Dependencies -->
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <!-- Exclude files from Ozone -->
            <id>Exclude unneeded Ozone files</id>
            <phase>process-resources</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>
                ${project.build.directory}/${project.artifactId}-${project.version}</outputDirectory>
              <overwrite>true</overwrite>
              <resources>
                <resource>
                  <directory>${project.build.directory}/ozone</directory>
                  <excludes>
                    <exclude>distro/**/addresshierarchy/*.*</exclude>
                    <exclude>distro/**/appointment*/*.*</exclude>
                    <exclude>distro/**/attributetypes/*.*</exclude>
                    <exclude>distro/**/concepts/*.*</exclude>
                    <exclude>distro/**/drugs*</exclude>
                    <exclude>distro/**/locations*</exclude>
                    <exclude>distro/**/ocl*</exclude>
                    <exclude>distro/**/patientidentifiertypes*</exclude>
                    <exclude>distro/**/program*</exclude>
                    <exclude>distro/**/relationshiptypes*</exclude>
                    <exclude>distro/**/visittypes*</exclude>
                    <exclude>distro/**/ampathforms/*.json</exclude>
                    <exclude>distro/**/ampathformstranslations/*.json</exclude>
                    <exclude>distro/**/globalproperties/i18n.xml</exclude>
                    <exclude>distro/**/*demo.*</exclude>
                  </excludes>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <repositories>
    <repository>
      <id>mks-nexus-public</id>
      <url>https://nexus.mekomsolutions.net/repository/maven-public/</url>
    </repository>
    <repository>
      <id>openmrs-repo</id>
      <name>OpenMRS Nexus Repository</name>
      <url>https://mavenrepo.openmrs.org/nexus/content/repositories/public</url>
    </repository>
    <repository>
      <id>sonatype-nexus-snapshots</id>
      <name>Sonatype Nexus Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

  <distributionManagement>
    <repository>
      <name>Mekom Solutions Nexus repo for releases</name>
      <id>mks-repo</id>
      <url>https://nexus.mekomsolutions.net/repository/maven-releases</url>
    </repository>
    <snapshotRepository>
      <name>Mekom Solutions Nexus repo for snapshots</name>
      <id>mks-repo-snapshots</id>
      <url>https://nexus.mekomsolutions.net/repository/maven-snapshots</url>
    </snapshotRepository>
  </distributionManagement>
</project>
```

Which isn't particularly short, but is much shorter than what's currently there. With this configuration, the ids of executions become very important, i.e., I had to use `<id>Exclude unneeded Ozone files</id>` to override the default exclusions and include a few more. I've tried to make things so `ozone-distro-parent` is pretty minimal.

### CODE REVIEW

**Comment by rbuisson** [comment]
Thanks @ibacher  I like this a lot. In fact I didn't know about the relative path for `<parent>` which appears to allow to use the pom of a project that's not even built yet. Thus also refer to it as a module.

I'd like to keep this change to after the `alpha.9` release though, as I suspect this will have consequences on other distributions (Oz Kh) Please correct me if I'm wrong.

**Comment by ibacher** [comment]
I'm completely on board with deferring this until the alpha.9 release is done.

**Review by rbuisson — CHANGES_REQUESTED** [review]
Thanks @ibacher

**Comment by ibacher** [comment]
@rbuisson Anything else need doing here?

**Comment by rbuisson** [comment]
We're all good @ibacher . Let me merge this right away.

**Pull request merged**
