### PR TITLE
Fixed parent distro validation temporarily.

### PR DESCRIPTION
**Pull request by Ruhanga**

### CODE REVIEW

**Comment by rbuisson** [comment]
Thank you for the PR @Ruhanga . I am a bit hesitant to disable this entirely as I like that people inheriting Ozone Parent will automatically get an OpenMRS validation working. This is actually needed by [KenyaHMIS](https://github.com/palladiumkenya/kenyahmis).

**Review by rbuisson — CHANGES_REQUESTED** [review]
@Ruhanga  could you simply comment out this execution, instead of deleting it, and drop a line of explanation along with it?

**Comment by ibacher** [comment]
@rbuisson I think I've come around to the idea that this will just need to be part of the Maven archetype maintained for Ozone projects rather than the parent. There's no obvious escape hatch in Maven to only run this profile if it's being executed as part of a child job.

**Comment by Ruhanga** [comment]
>  the idea that this will just need to be part of the Maven archetype maintained for Ozone projects rather than the parent.

I'm ok with it @ibacher. Feel free to close this, hoping that this could resolve soon so we can have published SNAPSHOTS.

**Pull request merged**
