### PR TITLE
maven-parent: Copy locally defined OMODs

### PR DESCRIPTION
**Pull request by ibacher**
The main goal of this PR is to enable copying any OMOD dependencies into to the OpenMRS modules directory. This is done using the same pattern as Ozone. I've also update the distribution itself to delete any non-OMOD JARs that are accidentally included by deleting them.

### CODE REVIEW

**Comment by ibacher** [comment]
cc: @rbuisson @Ruhanga @corneliouzbett I'd appreciate your reviews on this.

**Comment by rbuisson** [comment]
@ibacher , @corneliouzbett  had done [this](https://github.com/ozone-his/ozone/commit/d398c9f3819c768d7f095af2294b305c21f74036) in order to account for the issue of not copying non-omod dependencies. In that instance, excluding the Camel routes. Doesn't it suffice? Or do you anticipate possible other non-omods deps that should be removed?

**Comment by ibacher** [comment]
> Or do you anticipate possible other non-omods deps that should be removed?

I think it suffices for Ozone itself—and is actually a better solution than what I've implemented here. I was sort of anticipating "what happens if an Ozone FOSS user implements their own eip", but maybe that's not something we need to anticipate?

**Comment by rbuisson** [comment]
Well, fair enough. We might as well go for a solution that's generic enough.
Please remove the exclusion of `com.ozone` artifacts and go for the removal of anything that's been copied but is not an OMOD.

cc @corneliouzbett .

**Review by Ruhanga — COMMENTED** [review]
Makes sense @ibacher. This means the change done earlier goes away? @corneliouzbett?

https://github.com/ozone-his/ozone/pull/46/files#diff-9431c1fd5d949b517ad66f5f0b39479fe4e2368edc3a800c5c42ebd24bce0a21R128

**Comment by ibacher** [comment]
@Ruhanga I guess so, but it's harmless since I added a delete step to delete those files anyways.

**Comment by rbuisson** [comment]
@ibacher  could you take a look at those conflicts? Then we can merge.

**Comment by ibacher** [comment]
I was just working on resolving them. I think we should be good.

**Pull request merged**
